### PR TITLE
Simplified API, Added support for loading multiple paths

### PR DESCRIPTION
**Pull request by fjolnir**

### CODE REVIEW

**Comment by arielelkin** [comment]
@fjolnir: A lot of users have been asking for support for multiple paths and shapes:
https://github.com/arielelkin/PocketSVG/issues/7
https://github.com/arielelkin/PocketSVG/issues/30
https://github.com/arielelkin/PocketSVG/pull/35#issuecomment-114995195

If we could combine our efforts I think it'd be better for everybody, especially the users. 

How could we make it work this time? 

Ariel

**Comment by fjolnir** [comment]
There's no code shared between PocketSVG and my fork anymore so there's really no merging that can be done.

At this point https://github.com/fjolnir/SVGPathSerializing implements more SVG features so the most logical way to combine efforts would be to add support for more shape types there.

**Comment by arielelkin** [comment]
@fjolnir You have a point. And SVGPathSerializing does implement more SVG features than PocketSVG. But at the same time, SVGPathSerializing's user base is considerably smaller than PocketSVG's. 

Now, I want like to act in the interests of our users, so I don't want to brutally deprecate PocketSVG in favour of SVGPathSerializing, and manually tell people to migrate. 

I'm happy for there to be a transition, but I'd like it to be seamless for the users. 

However, there needs to be a migration either from PocketSVG to SVGPathSerializing, or from SVGPathSerializing to PocketSVG. Given that PocketSVG's user base is considerably bigger than SVGPathSerializing ([currently 500+](https://github.com/arielelkin/PocketSVG/stargazers) vs. [2](https://github.com/fjolnir/SVGPathSerializing/stargazers)), it'll be globally less painful for the users to go from SVGPathSerializing to PocketSVG. 

So how about this: we replace PocketSVG's SVG rendering engine (`PocketSVG.m`), with SVGPathSerializing's SVG rendering engine (`SVGPathSerializing.mm` + `SVGLayer.m`), we add the methods from `SVGPathSerializing.h` to `PocketSVG.h`, and the existing `PocketSVG.h` methods simply call SVGPathSerializing code. 

What do you think?

**Comment by fjolnir** [comment]
Having taken a look at the current PocketSVG API and ignoring deprecated methods the following looks like all you need for a compatibility shim: 
```objc
@implementation PocketSVG
+ (CGPathRef)pathFromSVGFileNamed:(NSString *)nameOfSVG
{
    return [self pathFromSVGFileAtURL:[[NSBundle mainBundle] URLForResource:nameOfSVG
                                                              withExtension:@"svg"]];
}

+ (CGPathRef)pathFromSVGFileAtURL:(NSURL *)svgFileURL
{
    return [self pathFromSVGString:[NSString stringWithContentsOfURL:svgFileURL
                                                            encoding:NSUTF8StringEncoding
                                                               error:NULL]];
}

+ (CGPathRef)pathFromSVGString:(NSString *)svgString;
{
    return (__bridge CGPathRef)[CGPathsFromSVGString(svgString, NULL) firstObject];
}

+ (CGPathRef)pathFromDAttribute:(NSString *)dAttribute
{
    return [self pathFromSVGString:[NSString stringWithFormat:
                                    @"<svg><path d=\"%@\"/></svg>", dAttribute
                                    ]];
}
@end
```

But of course this does not allow for multiple paths, so I don't really see a use for it.

**Comment by arielelkin** [comment]
@fjolnir : Yes, that compatibility shim you posted is indeed pretty simple. 

You're right that my current `pathFromSVGFileNamed`, `pathFromSVGString`, etc. don't allow for multiple paths. Still, I'd rather leave them in but explicitly `__attribute__((deprecated)` them. And add the new methods that support multiple paths. 

If you're happy with that, I'm happy to give you push rights to the PocketSVG repository, and we can take it from there. Yeah?

**Comment by arielelkin** [comment]
Hey @fjolnir ! Waiting to hear back from you. What are your thoughts?

**Comment by tikamchandrakar18** [comment]
Hi , I read all the above comment , its really nice feature and implementation.

But its true we need multiple path support feature. Could you provide us soon or will take some more time.

Please reply us . We are waitting for your reply.

Thanks in advance.
Tikam

**Comment by fjolnir** [comment]
Multiple paths are supported already.

**Comment by arielelkin** [comment]
@fjolnir: Yep, in SVGPathSerializing but not in PocketSVG. 

So allow me to reiterate the proposal I made you earlier. 

Let's merge our libraries together. With more than 700 stars and [4000 monthly downloads](https://cocoapods.org/pods/PocketSVG), PocketSVG has the largest userbase. But your SVGPathSerializing has many features they need, and which I don't have the time to manually merge or implement. 

At this stage, I'm completely ok with making a non-backwards-compatible v2 with an API that matches SVGPathSerializing's more closely and would make the merging easier. 

Would you like to merge PocketSVG and SVGPathSerializing and have commit access to PocketSVG?

**Comment by tikamchandrakar18** [comment]
We did little bit modify on pocket SVN to  Support Multiple path from single image. Please look at the changes below. I did it only for iOS , Need your suggestion . Now its working fine but may be in issues on other side. Please let us review it if you have time. thanks .
Tikam


Code Des: 

Getting array of Path:
Calling:  NSMutableArray *myPathArray = [PocketSVG pathFromSVGFileNamed:@"irregular__27"];

+ (NSMutableArray *)pathFromSVGFileNamed:(NSString *)nameOfSVG
{
    NSMutableArray *path = [[NSMutableArray alloc] init];
    NSArray *parseSVG = [self parseSVGNamed:nameOfSVG];
    
    for(int start = 0;start<parseSVG.count ; start++){
        PocketSVG *pocketSVG = [PocketSVG pocketSVGFromSVGPathNodeDAttr:[parseSVG objectAtIndex:start]];
       
        pocketSVG.bezier.flatness = 1;
        [path addObject:pocketSVG.bezier];
 
    }
    
    
//PocketSVG *pocketSVG = [PocketSVG pocketSVGFromSVGPathNodeDAttr:parseSVG];
    
#if TARGET_OS_IPHONE

    return path;
#else
    return path;
#endif
}

/********
 Returns the content of the SVG's d attribute as an NSString
 */
+ (NSArray *)parseSVGNamed:(NSString *)nameOfSVG{
#if !TARGET_INTERFACE_BUILDER
    NSBundle *bundle = [NSBundle mainBundle];
#else
    NSBundle *bundle = [NSBundle bundleForClass:[self class]];
#endif
    
    NSString *pathOfSVGFile = [bundle pathForResource:nameOfSVG ofType:@"svg"]; // Use 'bundleForClass' instead of 'mainBundle' for Interface Builder Designable compatibility.
    
    if(pathOfSVGFile == nil){
        NSLog(@"*** PocketSVG Error: No SVG file named \"%@\".", nameOfSVG);
        return nil;
    }
    
    NSError *error = nil;
    NSString *mySVGString = [NSString stringWithContentsOfFile:pathOfSVGFile encoding:NSStringEncodingConversionExternalRepresentation error:&error];
    
    if(error != nil){
        NSLog(@"*** PocketSVG Error: Couldn't read contents of SVG file named %@:", nameOfSVG);
        NSLog(@"%@", error);
        return nil;
    }
    
    return [[self class] dStringFromRawSVGString:mySVGString];
}

+ (NSArray*)dStringFromRawSVGString:(NSString*)svgString{
    //Uncomment the two lines below to print the raw data of the SVG file:
    //NSLog(@"*** PocketSVG: Raw SVG data of %@:", nameOfSVG);
    //NSLog(@"%@", mySVGString);

    svgString = [svgString stringByReplacingOccurrencesOfString:@"id=" withString:@""];
    
    NSLog(@" svgString %@", svgString);
    
    
    
    NSArray *components = [svgString componentsSeparatedByString:@"d="];
    
    
    NSLog( @"components %lu",(unsigned long)components.count);
    
    if([components count] < 2){
        NSLog(@"*** PocketSVG Error: No d attribute found in SVG file.");
        return nil;
    }
    
    NSMutableArray *pathArray = [[NSMutableArray alloc] init];
    
    
    for(int path = 1; path < components.count; path++)
    {
    
    NSString *dString = [components objectAtIndex:path];
 [](url)    dString = [dString substringFromIndex:1];
    NSRange d = [dString rangeOfString:@"\""];
    dString = [dString substringToIndex:d.location];
    dString = [dString stringByReplacingOccurrencesOfString:@" " withString:@","];
    NSArray *dStringWithPossibleWhiteSpace = [dString componentsSeparatedByCharactersInSet:[NSCharacterSet newlineCharacterSet]];
    
    dString = [dStringWithPossibleWhiteSpace componentsJoinedByString:@""];
        
    [pathArray addObject:dString];
        
    }
    //Uncomment the line below to print the raw path data of the SVG file:
    //NSLog(@"*** PocketSVG: Path data of %@ is: %@", nameOfSVG, dString);


    
    return pathArray;
}


[zip.zip](https://github.com/arielelkin/PocketSVG/files/265565/zip.zip)

**Comment by Shmaff** [comment]
I'm here for moral support! None of the current SVG rendering libraries out there for Objective-C or Swift are complete. I've tried four (4) and I haven't had the time to get my hands dirty yet myself. I've both both of yours (@arielelkin and @fjolnir) to be the most useful so I would be happy to see some collaboration here! The others out there are fat libraries that have peculiar, ailing bugs. Best of luck!

**Comment by fjolnir** [comment]
Superseded by https://github.com/arielelkin/PocketSVG/pull/47

**Pull request closed without merging**
