### PR TITLE
Support Quadratic Bézier paths

### PR DESCRIPTION
**Pull request by dbworku**
Adds support for:
- Quadratic Bézier (Q,q)
- Smooth quadratic Bézier (T,t)

SVG 1.1: [Quadratic Bezier Commands](http://www.w3.org/TR/SVG/paths.html#PathDataQuadraticBezierCommand)

*Note:* NSBezierPath doesn't support adding quadratic curves. The approximation using the cubic bezier function should be very accurate unless the path is scaled extremely large.

### CODE REVIEW

**Comment by arielelkin** [comment]
Hey @dbworku , thanks for this pull request. 

I tested it with a couple of SVGs with `q` and `t`, it works fine :)

Question: why did you do those modifications to `appendSVGMCommand` and  `appendSVGCCommand`?

Cheers

Ariel

**Comment by dbworku** [comment]
@arielelkin I created the PocketSVGControlPoint enum (and modified the other methods) because the last control point's validity depends on which curve set the point. 

8.3.7 The quadratic Bézier curve commands
> If there is no previous command or if the previous command was not a Q, q, T or t, assume the control point is coincident with the current point.

8.3.6 The cubic Bézier curve commands
> If there is no previous command or if the previous command was not an C, c, S or s, assume the first control point is coincident with the current point.

We need to update the control point's state in all methods. However, your question brings up that `appendSVGSCommand` is actually not fully compliant. I'll make a commit on this pull and bump you.

**Comment by arielelkin** [comment]
Sounds good!

**Comment by dbworku** [comment]
@arielelkin How does it look?

**Comment by arielelkin** [comment]
Pretty good, thank you!

**Pull request merged**
