### PR TITLE
Carthage

### PR DESCRIPTION
**Pull request by halseth**
carthage support

### CODE REVIEW

**Comment by arielelkin** [comment]
@halseth thanks for submitting this. 

Can this be reopened? Is there anything missing?

**Comment by halseth** [comment]
It was submitted by a mistake, but if you are interested I can create a new PR. It is for support with Carthage.

**Comment by arielelkin** [comment]
Yes I'm interested, please do :-)

**Comment by halseth** [comment]
will open a new one with the correct branch

**Pull request closed without merging**
